name: clonify
description: A powerful CLI tool for managing multiple Flutter project clones with different configurations, branding, Firebase, and Shorebird. Perfect for white-label apps.
version: 0.6.0
homepage: https://github.com/gailansoran4/clonify
repository: https://github.com/gailansoran4/clonify
issue_tracker: https://github.com/gailansoran4/clonify/issues

topics:
  - cli
  - flutter
  - white-label
  - multi-tenant
  - clone

environment:
  sdk: ^3.13.0

platforms:
  linux:
  macos:
  windows:

dependencies:
  args: ^2.7.0
  logger: ^2.6.1
  mason_logger: ^0.3.3
  chalkdart: ^3.0.5
  crypto: ^3.0.6
  path: ^1.9.1
  yaml_edit: ^2.2.2
  yaml: ^3.1.3
  html: ^0.15.6

dev_dependencies:
  lints: ^5.0.0
  test: ^1.26.3

executables:
  clonify:
