import 'dart:convert';

import 'profile_schema.dart';

import 'dart:io';

import '../custom_exceptions.dart';
import '../models/config_model.dart';
import '../models/color_model.dart';
import '../src/clonify_core.dart';
import 'notification_icon_manager.dart';

/// Escapes data as a Dart string literal, including interpolation characters.
String dartString(String value) {
  final escaped = jsonEncode(value);
  return "'${escaped.substring(1, escaped.length - 1).replaceAll(r'\"', '"').replaceAll("'", r"\'").replaceAll(r'$', r'\$')}'";
}

/// Generates app-visible values only. Credential references never enter Dart.
Future<void> generateCloneConfigFile(CloneConfigModel model) async {
  for (final entry in {
    'client_id': model.clientId,
    'android_package_name': model.androidPackageName,
    'ios_package_name': model.iosPackageName,
    'app_name': model.appName,
    'version': model.version,
    'logo': model.logo,
    'launcher_icon': model.launcherIcon,
    'splash_screen': model.splashScreen,
  }.entries) {
    if (entry.value == null || entry.value!.trim().isEmpty) {
      throw CustomException(
        'Cannot generate config: ${entry.key} is required.',
      );
    }
  }
  final color = notificationColorArgbLiteral(
    (model.backgroundNotificationColor?.isNotEmpty ?? false)
        ? model.backgroundNotificationColor!
        : model.primaryColor ?? '',
  );
  final output = StringBuffer(
    '// Generated by Clonify. Edit the profile config instead.\n',
  );
  if ((model.colors?.isNotEmpty ?? false) || color != null) {
    output.writeln("import 'dart:ui';\n");
  }
  output.writeln('abstract class CloneConfigs() {');
  final fields = <String, String>{
    if (model.baseUrl != null) 'baseUrl': model.baseUrl!,
    'androidPackageName': model.androidPackageName ?? '',
    'iosPackageName': model.iosPackageName ?? '',
    'appName': '${model.appName}',
    'logo': 'assets/images/${model.logo}',
    'launcherIcon': 'assets/images/${model.launcherIcon}',
    'splashScreen': 'assets/images/${model.splashScreen}',
    if (model.firebaseProjectId?.isNotEmpty ?? false)
      'firebaseProjectId': model.firebaseProjectId!,
    if (model.shorebirdAppId?.isNotEmpty ?? false)
      'shorebirdAppId': model.shorebirdAppId!,
    'clientId': '${model.clientId}',
    'version': model.version,
    if (model.primaryColor != null) 'primaryColor': model.primaryColor!,
  };
  final names = {...fields.keys, 'backgroundNotificationColor'};
  for (final entry in fields.entries) {
    output.writeln(
      '  static const String ${entry.key} = ${dartString(entry.value)};',
    );
  }
  if (color != null) {
    output.writeln(
      '  static const Color backgroundNotificationColor = Color($color);',
    );
  }
  for (final item in model.colors ?? <ColorModel>[]) {
    if (item.name == null || item.color == null) {
      throw CustomException('Every color needs name and color.');
    }
    final name = camelCaseField(item.name!);
    assertGeneratedFieldName(name, names);
    if (!RegExp(r'^[0-9a-fA-F]{6}$').hasMatch(item.color!)) {
      throw CustomException('Color ${item.name} must contain six hex digits.');
    }
    output.writeln('  static const $name = Color(0xFF${item.color});');
  }
  final settings = getClonifySettings();
  if (settings.customFields.isNotEmpty) {
    final config = jsonDecode(
      File('clonify/clones/${model.clientId}/config.json').readAsStringSync(),
    ) as Map<String, dynamic>;
    final normalized = normalizeProfile(config);
    for (final field in settings.customFields) {
      final name = camelCaseField(field.name);
      assertGeneratedFieldName(name, names);
      if (name == 'firebaseServiceAccount') {
        throw CustomException(
          'firebaseServiceAccount cannot be an app custom field.',
        );
      }
      final value = normalized[name];
      if (value == null) continue;
      final valid = switch (field.type) {
        'int' => value is int,
        'double' => value is num && value.isFinite,
        'bool' => value is bool,
        'string' => value is String,
        _ => false,
      };
      if (!valid) {
        throw CustomException(
          'Custom field ${field.name} must have type ${field.type}.',
        );
      }
      final type = field.type == 'string' ? 'String' : field.type;
      final literal = value is String
          ? dartString(value)
          : field.type == 'double'
          ? (value as num).toDouble().toString()
          : '$value';
      output.writeln('  static const $type $name = $literal;');
    }
  }
  output.writeln('}');
  final file = File('lib/generated/clone_configs.dart');
  file.parent.createSync(recursive: true);
  file.writeAsStringSync(output.toString(), flush: true);
}

void assertGeneratedFieldName(String name, Set<String> names) {
  const reserved = {
    'CloneConfigs',
    'hashCode',
    'runtimeType',
    'toString',
    'noSuchMethod',
    'class',
    'const',
    'static',
    'final',
    'var',
    'void',
    'int',
    'double',
    'bool',
    'String',
    'return',
    'if',
    'else',
    'for',
    'while',
    'switch',
    'case',
    'default',
    'new',
    'this',
    'super',
    'true',
    'false',
    'null',
    'throw',
    'try',
    'catch',
    'finally',
    'extends',
    'with',
    'implements',
    'enum',
    'mixin',
    'typedef',
    'import',
    'export',
    'part',
    'library',
    'assert',
    'await',
    'yield',
    'break',
    'continue',
    'do',
    'in',
    'is',
    'rethrow',
  };
  if (!RegExp(r'^[a-zA-Z][a-zA-Z0-9_]*$').hasMatch(name) ||
      reserved.contains(name) ||
      !names.add(name)) {
    throw CustomException('Invalid or duplicate generated field name: $name');
  }
}
